// ============================================================
// top.sv — Integrated Top Module
// Project : 256-pt FFT Vibration Anomaly Detection Accelerator
// Course  : ECE 410/510 HW4AI, Spring 2026
// Author  : Yaqoub Rabiah
//
// Description:
//   Integration module that connects the SPI slave interface
//   (spi_slave) to the radix-2 butterfly compute core (compute_core)
//   through a finite-state-machine glue layer.
//
//   The host communicates exclusively through the SPI port. No
//   compute-core signals are exposed externally. The FSM unpacks
//   incoming SPI words into butterfly operands, fires the compute
//   core for one cycle, waits for valid_out, latches the four
//   output words, and presents them to the host via MISO on
//   subsequent SPI read transactions.
//
// SPI Protocol (16-bit words per transaction, Mode 0):
//   WRITE phase — host sends 7 consecutive words:
//     Word 0 : WRITE_CMD (0x0001)  → start of write sequence
//     Word 1 : ar_in               → A real  (Q1.15 signed)
//     Word 2 : ai_in               → A imag
//     Word 3 : br_in               → B real
//     Word 4 : bi_in               → B imag
//     Word 5 : wr_in               → twiddle W real
//     Word 6 : wi_in               → twiddle W imag (fires compute)
//
//   READ phase — host sends 4 more words (READ_CMD + 3 NOPs):
//     Word 0 : READ_CMD (0x0002)  MISO = ar_out
//     Word 1 : NOP (0x0000)       MISO = ai_out
//     Word 2 : NOP (0x0000)       MISO = br_out
//     Word 3 : NOP (0x0000)       MISO = bi_out
//
// Glue logic:
//   The tx_data mux is combinational: it presents the correct
//   output register on tx_data so that the spi_slave loads it
//   into its TX shift register when cs_n falls at the start of
//   each read transaction. No FIFO required; output registers
//   hold results until the next WRITE_CMD.
//
// Port list:
//   clk       in   1    system clock (100 MHz)
//   rst       in   1    synchronous active-high reset
//   spi_sclk  in   1    SPI serial clock from master (async)
//   spi_cs_n  in   1    SPI chip-select, active-low (async)
//   spi_mosi  in   1    master→slave data (async)
//   spi_miso  out  1    slave→master data
//
// Clock domain : single (clk)
// Reset        : synchronous, active-high (rst)
// ============================================================

`timescale 1ns/1ps

module top (
    input  logic clk,
    input  logic rst,
    // SPI port — only external signals; compute core is internal
    input  logic spi_sclk,
    input  logic spi_cs_n,
    input  logic spi_mosi,
    output logic spi_miso
);

    // ------------------------------------------------------------------
    // Commands
    // ------------------------------------------------------------------
    localparam [15:0] WRITE_CMD = 16'h0001;
    localparam [15:0] READ_CMD  = 16'h0002;

    // ------------------------------------------------------------------
    // SPI slave instance
    // ------------------------------------------------------------------
    logic [15:0] rx_data;
    logic        rx_valid;
    logic [15:0] tx_data;

    spi_slave u_spi (
        .clk      (clk),
        .rst      (rst),
        .spi_sclk (spi_sclk),
        .spi_cs_n (spi_cs_n),
        .spi_mosi (spi_mosi),
        .spi_miso (spi_miso),
        .rx_data  (rx_data),
        .rx_valid (rx_valid),
        .tx_data  (tx_data)
    );

    // ------------------------------------------------------------------
    // Compute core instance
    // Inputs are driven from latched registers; valid_in is a 1-cycle
    // pulse generated by the FSM when all six operands are ready.
    // ------------------------------------------------------------------
    logic signed [15:0] ar_r, ai_r, br_r, bi_r, wr_r, wi_r;
    logic               core_valid_in;
    logic               core_valid_out;
    logic signed [15:0] ar_out, ai_out, br_out, bi_out;

    compute_core u_core (
        .clk       (clk),
        .rst       (rst),
        .valid_in  (core_valid_in),
        .ar_in     (ar_r),
        .ai_in     (ai_r),
        .br_in     (br_r),
        .bi_in     (bi_r),
        .wr_in     (wr_r),
        .wi_in     (wi_r),
        .valid_out (core_valid_out),
        .ar_out    (ar_out),
        .ai_out    (ai_out),
        .br_out    (br_out),
        .bi_out    (bi_out)
    );

    // ------------------------------------------------------------------
    // FSM — 12 states
    // ------------------------------------------------------------------
    typedef enum logic [3:0] {
        S_IDLE,   // waiting for WRITE_CMD
        S_AR,     // next rx_data = ar_in
        S_AI,     // next rx_data = ai_in
        S_BR,     // next rx_data = br_in
        S_BI,     // next rx_data = bi_in
        S_WR,     // next rx_data = wr_in
        S_WI,     // next rx_data = wi_in → fire compute
        S_WAIT,   // waiting for core_valid_out
        S_RDY,    // results ready; tx_data = ar_res; waiting for READ_CMD
        S_SAI,    // READ_CMD received; tx_data = ai_res
        S_SBR,    // ai sent;           tx_data = br_res
        S_SBI     // br sent;           tx_data = bi_res
    } state_t;

    state_t state;

    // Output result registers (latched when core_valid_out fires)
    logic signed [15:0] ar_res, ai_res, br_res, bi_res;

    always_ff @(posedge clk) begin
        if (rst) begin
            state         <= S_IDLE;
            core_valid_in <= 1'b0;
            ar_r  <= '0;  ai_r  <= '0;
            br_r  <= '0;  bi_r  <= '0;
            wr_r  <= '0;  wi_r  <= '0;
            ar_res <= '0; ai_res <= '0;
            br_res <= '0; bi_res <= '0;
        end else begin
            core_valid_in <= 1'b0;   // default: deasserted every cycle

            case (state)
                // ---- Write phase ------------------------------------------
                S_IDLE: if (rx_valid && rx_data == WRITE_CMD) state <= S_AR;

                S_AR: if (rx_valid) begin
                    ar_r  <= $signed(rx_data);
                    state <= S_AI;
                end

                S_AI: if (rx_valid) begin
                    ai_r  <= $signed(rx_data);
                    state <= S_BR;
                end

                S_BR: if (rx_valid) begin
                    br_r  <= $signed(rx_data);
                    state <= S_BI;
                end

                S_BI: if (rx_valid) begin
                    bi_r  <= $signed(rx_data);
                    state <= S_WR;
                end

                S_WR: if (rx_valid) begin
                    wr_r  <= $signed(rx_data);
                    state <= S_WI;
                end

                // On wi_in receipt: latch wi, fire valid_in for one cycle.
                // ar_r..wr_r were latched in previous states; wi_r latches
                // here and will be stable by the cycle valid_in is sampled
                // by compute_core (non-blocking: both update at next posedge).
                S_WI: if (rx_valid) begin
                    wi_r          <= $signed(rx_data);
                    core_valid_in <= 1'b1;
                    state         <= S_WAIT;
                end

                // ---- Compute phase ----------------------------------------
                // compute_core has 3-cycle latency; wait for valid_out pulse
                S_WAIT: if (core_valid_out) begin
                    ar_res <= ar_out;
                    ai_res <= ai_out;
                    br_res <= br_out;
                    bi_res <= bi_out;
                    state  <= S_RDY;
                end

                // ---- Read phase -------------------------------------------
                // In S_RDY: combinational tx_data = ar_res.
                // When READ_CMD arrives, ar_res is already being shifted out
                // (slave loaded tx_data on cs_n fall, before READ_CMD arrived).
                // State advances to S_SAI so next cs_n fall loads ai_res.
                S_RDY: if (rx_valid && rx_data == READ_CMD) state <= S_SAI;

                S_SAI: if (rx_valid) state <= S_SBR;

                S_SBR: if (rx_valid) state <= S_SBI;

                S_SBI: if (rx_valid) state <= S_IDLE;

                default: state <= S_IDLE;
            endcase
        end
    end

    // ------------------------------------------------------------------
    // TX data mux — combinational so tx_data is stable before cs_n falls
    // ------------------------------------------------------------------
    always_comb begin
        case (state)
            S_RDY:   tx_data = ar_res;
            S_SAI:   tx_data = ai_res;
            S_SBR:   tx_data = br_res;
            S_SBI:   tx_data = bi_res;
            default: tx_data = 16'h0000;
        endcase
    end

endmodule
