// ============================================================
// mac_llm_A.v
// Generated by: Claude Sonnet 4.6
// Prompt: Synthesizable SystemVerilog MAC unit.
//   Module name: mac
//   Inputs:  clk (1-bit), rst (1-bit active-high synchronous),
//            a (8-bit signed), b (8-bit signed)
//   Output:  out (32-bit signed accumulator)
//   Behavior: on rising edge, rst -> out=0; else out += a*b
//   Constraints: synthesizable SV only, always_ff, no initial,
//                no $display, no delays.
// ============================================================

module mac (
    input  logic              clk,
    input  logic              rst,
    input  logic signed [7:0] a,
    input  logic signed [7:0] b,
    output logic signed [31:0] out
);

    // Compute signed 16-bit product combinationally
    logic signed [15:0] product;
    always_comb begin
        product = a * b;
    end

    always_ff @(posedge clk) begin
        if (rst)
            out <= 32'sd0;
        else
            out <= out + $signed({{16{product[15]}}, product});
    end

endmodule
