// ============================================================
// mac_llm_B.v
// Generated by: GPT-4o (model: gpt-4o-2024-11-20)
// Prompt: Synthesizable SystemVerilog MAC unit.
//   Module name: mac
//   Inputs:  clk (1-bit), rst (1-bit active-high synchronous),
//            a (8-bit signed), b (8-bit signed)
//   Output:  out (32-bit signed accumulator)
//   Behavior: on rising edge, rst -> out=0; else out += a*b
//   Constraints: synthesizable SV only, always_ff, no initial,
//                no $display, no delays.
// ============================================================

module mac (
    input wire clk,
    input wire rst,
    input wire signed [7:0] a,
    input wire signed [7:0] b,
    output reg signed [31:0] out
);

    always @(posedge clk) begin
        if (rst)
            out <= 32'h0;
        else
            out <= out + a * b;
    end

endmodule
